"""
End-to-end programmatic verification script for the platform.
"""
import sys
import time
import requests
from app.db.session import SessionLocal, verify_db_connection
from app.models.user import User, UserRole
from app.core.security import hash_password
from app.services.rag_service import store_document_chunks, retrieve_chunks
from app.crud.user import crud_user


def test_db():
    print("1. Verifying Database Connectivity...")
    if not verify_db_connection():
        print("FAILED: Database is not reachable.")
        sys.exit(1)
    print("SUCCESS: Database connection verified.")


def test_user_creation():
    print("\n2. Verifying User Creation and Database Persistence...")
    db = SessionLocal()
    try:
        # Clear existing test user if any
        existing = db.query(User).filter(User.email == "auditor@company.com").first()
        if existing:
            db.delete(existing)
            db.commit()

        # Create user
        user = crud_user.create_user(
            db,
            email="auditor@company.com",
            full_name="Compliance Auditor",
            hashed_password=hash_password("Auditor123!"),
            role=UserRole.AUDITOR
        )
        print(f"SUCCESS: User 'auditor@company.com' created with ID: {user.id}")
        assert user.role == UserRole.AUDITOR
        assert user.full_name == "Compliance Auditor"
        assert user.is_active is True
    except Exception as e:
        db.rollback()
        print("FAILED user creation:", e)
        sys.exit(1)
    finally:
        db.close()


def test_login():
    print("\n3. Verifying Login API & JWT Token Generation...")
    url = "http://localhost:8000/api/v1/auth/login"
    
    # Test Admin login
    payload_admin = {
        "email": "admin@company.com",
        "password": "Admin123!"
    }
    response_admin = requests.post(url, json=payload_admin)
    if response_admin.status_code != 200:
        print(f"FAILED: Admin login failed with status code {response_admin.status_code}")
        sys.exit(1)
    data_admin = response_admin.json()
    assert "access_token" in data_admin
    assert data_admin["token_type"] == "bearer"
    print("SUCCESS: Admin login succeeds and returns access_token.")

    # Test Auditor login
    payload_auditor = {
        "email": "auditor@company.com",
        "password": "Auditor123!"
    }
    response_auditor = requests.post(url, json=payload_auditor)
    if response_auditor.status_code != 200:
        print(f"FAILED: Auditor login failed with status code {response_auditor.status_code}")
        sys.exit(1)
    data_auditor = response_auditor.json()
    assert "access_token" in data_auditor
    print("SUCCESS: Auditor login succeeds.")
    return data_auditor["access_token"]


def test_rag_ingest():
    print("\n4. Verifying ChromaDB retrieval and semantic search...")
    # Inject test chunks to ensure we have content
    policy_chunks = [
        "Company Policy: Data storage must use encrypted servers. Access is restricted to authorized personnel.",
        "Company Policy: Remote access requires multi-factor authentication (MFA) and VPN."
    ]
    regulation_chunks = [
        "Regulation: All user data must be encrypted at rest and in transit. Multifactor authentication is required."
    ]
    
    try:
        store_document_chunks(policy_chunks, "test_policy.pdf", "policy")
        store_document_chunks(regulation_chunks, "test_regulation.pdf", "regulation")
        
        # Test semantic search retrieval
        retrieved = retrieve_chunks("MFA encryption")
        assert len(retrieved.get("documents", [])) > 0
        print(f"SUCCESS: ChromaDB semantic search returned {len(retrieved['documents'])} relevant chunks.")
    except Exception as e:
        print("FAILED ChromaDB check:", e)
        sys.exit(1)


def test_report_generation(token: str):
    print("\n5. Verifying Report Generation and Persistence...")
    url_report = "http://localhost:8000/api/v1/compliance/report"
    headers = {"Authorization": f"Bearer {token}"}
    
    response = requests.post(url_report, headers=headers)
    if response.status_code != 201:
        print(f"FAILED: Report generation failed with status code {response.status_code}")
        print(response.text)
        sys.exit(1)
    
    data = response.json()
    print("SUCCESS: Report successfully generated by LLM and persisted.")
    print(f"  - Generated Report ID: {data.get('id')}")
    print(f"  - Risk: {data.get('risk')}")
    print(f"  - Compliance Score: {data.get('compliance_score')}%")
    print(f"  - Violation Count: {data.get('violation_count')}")
    assert "id" in data
    assert "issues" in data
    assert "recommendations" in data
    return data["id"]


def test_dashboard_stats(token: str):
    print("\n6. Verifying Dashboard Analytics Endpoint...")
    url = "http://localhost:8000/api/v1/dashboard/stats"
    headers = {"Authorization": f"Bearer {token}"}
    
    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        print(f"FAILED: Dashboard stats endpoint failed with status code {response.status_code}")
        sys.exit(1)
    
    data = response.json()
    print("SUCCESS: Dashboard statistics retrieved:")
    print(f"  - Total Audits: {data.get('total_audits')}")
    print(f"  - Average Compliance Score: {data.get('average_compliance_score')}%")
    assert data.get("total_audits", 0) > 0


def cleanup():
    print("\n7. Cleaning up test data...")
    db = SessionLocal()
    try:
        user = db.query(User).filter(User.email == "auditor@company.com").first()
        if user:
            # Delete user's audits
            from app.models.audit_report import AuditReport
            db.query(AuditReport).filter(AuditReport.created_by_user_id == user.id).delete()
            db.delete(user)
            db.commit()
            print("Successfully cleaned up test auditor and associated reports.")
    except Exception as e:
        db.rollback()
        print("Error during cleanup:", e)
    finally:
        db.close()


if __name__ == "__main__":
    test_db()
    test_user_creation()
    token = test_login()
    test_rag_ingest()
    test_report_generation(token)
    test_dashboard_stats(token)
    cleanup()
    print("\n" + "="*50)
    print("ALL API SMOKE TESTS COMPLETED SUCCESSFULLY")
    print("="*50)
